### ISSUE TITLE
One working example would be useful...

### ISSUE THREAD

**Issue by jahagirdar** [b10m/p5-Dancer2-Plugin-Auth-OAuth#9]
I have written oauth code in Dancer1, For my current project I am testing the infrastructure for Dancer2 and I am lost as to what should be done after plugging in my (twitter) tokens in the config file :(
I tried browsing to <localhost.domain>/auth/twitter which redirects me to the auth-error page

If there is a sample Dancer app it would help in understanding the module...

**Comment by b10m** [comment]
You could have a look at the tests that come with the module, or just use this extremely basic app (and do double check your twitter client_id and client_token are correct.

```
package App;

use Dancer2;
use Dancer2::Plugin::Auth::OAuth;

get '/' => sub {
    return "hi there!";
};

1;
```

With a config.yaml like:

```
plugins:
  "Auth::OAuth":
    success_url: /users
    error_url: /?error=1
    providers:
      Twitter:
        tokens:
          consumer_key: <TWITTER_CONSUMER_KEY>
          consumer_secret: <TWITTER_CONSUMER_SECRET>
```

Calling /auth/twitter after on this will result in a redirect to twitter's authentication page.
